[package]
name = "test-case-derive"
version = "0.2.3"
authors = ["Marcin Sas-Szymanski <marcin.sas-szymanski@anixe.pl>"]
description = "Provides #[test_case(...)] procedural macro attribute for generating parametrized test cases easily"
keywords = ["test", "case", "tests", "unit", "testing"]
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/synek317/test-case-derive"
documentation = "https://docs.rs/test-case-derive"

[badges]
travis-ci = { repository = "synek317/test-case-derive", branch = "master" }
maintenance = { status = "deprecated" }

[lib]
doctest = false
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
lazy_static = "0.2.8"
